require("fs.plugins.neotree")
-- require("fs.plugins.configuration.nvim-tree")
require("fs.plugins.bufferline")
require("fs.plugins.lualine")
require("fs.plugins.bufdelete")
require("fs.plugins.telescope")
