require("fs.plugins.neotree")
-- require("fs.plugins.configuration.nvim-tree")
require("fs.plugins.bufferline")
require("fs.plugins.lualine")
require("fs.plugins.telescope")
require("fs.plugins.treesitter")
require("fs.plugins.cmp")
require("fs.plugins.closebuffers")
