require("fs.plugins.bootstrap_packer")
require("fs.plugins.dependencies")
require("fs.plugins.configuration.neotree")
-- require("fs.plugins.configuration.nvim-tree")
require("fs.plugins.configuration.bufferline")
require("fs.plugins.configuration.lualine")
require("fs.plugins.configuration.bufdelete")
require("fs.plugins.configuration.telescope")
